/* config.h.cmake — generated by CMake from cmake/config.h.cmake */

/* Define build-type */
#define BUILD "${HAVE_BUILD}"

/* Define build-type */
#define HOST "${HAVE_HOST}"

/* Define target-type */
#define TARGET "${HAVE_TARGET}"

/* Name of package */
#define PACKAGE "${PROJECT_NAME}"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "https://github.com/Kenshin9977/aria2/issues"

/* Define to the full name of this package. */
#define PACKAGE_NAME "${PROJECT_NAME}"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "${PROJECT_NAME} ${PROJECT_VERSION}"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "${PROJECT_NAME}"

/* Define to the home page for this package. */
#define PACKAGE_URL "https://aria2.github.io/"

/* Define to the version of this package. */
#define PACKAGE_VERSION "${PROJECT_VERSION}"

/* Version number of package */
#define VERSION "${PROJECT_VERSION}"

/* Define to 1 if all of the C89 standard headers exist. */
#define STDC_HEADERS 1

/* ── Feature flags ── */

#cmakedefine ENABLE_SSL 1
#cmakedefine ENABLE_BITTORRENT 1
#cmakedefine ENABLE_METALINK 1
#cmakedefine ENABLE_WEBSOCKET 1
#cmakedefine ENABLE_XML_RPC 1
#cmakedefine ENABLE_ASYNC_DNS 1
#cmakedefine ENABLE_NLS 1

/* ── Library detection ── */

#cmakedefine HAVE_WINTLS 1
#cmakedefine HAVE_LIBGNUTLS 1
#cmakedefine HAVE_OPENSSL 1
#cmakedefine HAVE_LIBNETTLE 1
#cmakedefine HAVE_LIBGMP 1
#cmakedefine HAVE_LIBGCRYPT 1
#cmakedefine HAVE_ZLIB 1
#cmakedefine HAVE_SQLITE3 1
#cmakedefine HAVE_LIBXML2 1
#cmakedefine HAVE_LIBEXPAT 1
#cmakedefine HAVE_LIBCARES 1
#cmakedefine HAVE_LIBSSH2 1
#cmakedefine HAVE_LIBNGHTTP2 1
#cmakedefine HAVE_LIBUV 1

/* ── Message digest implementation ── */

#cmakedefine USE_OPENSSL_MD 1
#cmakedefine USE_LIBNETTLE_MD 1
#cmakedefine USE_LIBGCRYPT_MD 1
#cmakedefine USE_INTERNAL_MD 1

/* ── Crypto implementations ── */

#cmakedefine USE_INTERNAL_BIGNUM 1
#cmakedefine USE_INTERNAL_ARC4 1

/* ── Platform features ── */

#cmakedefine HAVE_EPOLL 1
#cmakedefine HAVE_IOURING 1
#cmakedefine HAVE_KQUEUE 1
#cmakedefine HAVE_POLL 1
#cmakedefine HAVE_PORT_ASSOCIATE 1
#cmakedefine HAVE_SOME_FALLOCATE 1
#cmakedefine HAVE_POSIX_FALLOCATE 1
#cmakedefine HAVE_FALLOCATE 1
#cmakedefine KEVENT_UDATA_INTPTR_T 1
#cmakedefine HAVE_OPTION_CONST_NAME 1

/* ── Struct members ── */

#cmakedefine HAVE_SOCKADDR_IN_SIN_LEN 1
#cmakedefine HAVE_SOCKADDR_IN6_SIN6_LEN 1
#cmakedefine HAVE_A2_STRUCT_TIMESPEC 1

/* ── Header files ── */

#cmakedefine HAVE_ARGZ_H 1
#cmakedefine HAVE_ARPA_INET_H 1
#cmakedefine HAVE_FCNTL_H 1
#cmakedefine HAVE_FLOAT_H 1
#cmakedefine HAVE_IFADDRS_H 1
#cmakedefine HAVE_INTTYPES_H 1
#cmakedefine HAVE_IO_H 1
#cmakedefine HAVE_IPHLPAPI_H 1
#cmakedefine HAVE_LANGINFO_H 1
#cmakedefine HAVE_LIBINTL_H 1
#cmakedefine HAVE_LIMITS_H 1
#cmakedefine HAVE_LOCALE_H 1
#cmakedefine HAVE_MALLOC_H 1
#cmakedefine HAVE_NETDB_H 1
#cmakedefine HAVE_NETINET_IN_H 1
#cmakedefine HAVE_NETINET_TCP_H 1
#cmakedefine HAVE_POLL_H 1
#cmakedefine HAVE_PORT_H 1
#cmakedefine HAVE_PWD_H 1
#cmakedefine HAVE_SIGNAL_H 1
#cmakedefine HAVE_STDDEF_H 1
#cmakedefine HAVE_STDINT_H 1
#cmakedefine HAVE_STDIO_EXT_H 1
#cmakedefine HAVE_STDLIB_H 1
#cmakedefine HAVE_STRING_H 1
#cmakedefine HAVE_STRINGS_H 1
#cmakedefine HAVE_SYS_IOCTL_H 1
#cmakedefine HAVE_SYS_PARAM_H 1
#cmakedefine HAVE_SYS_RESOURCE_H 1
#cmakedefine HAVE_SYS_SIGNAL_H 1
#cmakedefine HAVE_SYS_SOCKET_H 1
#cmakedefine HAVE_SYS_TIME_H 1
#cmakedefine HAVE_SYS_TYPES_H 1
#cmakedefine HAVE_SYS_UIO_H 1
#cmakedefine HAVE_SYS_UTSNAME_H 1
#cmakedefine HAVE_TERMIOS_H 1
#cmakedefine HAVE_UNISTD_H 1
#cmakedefine HAVE_UTIME_H 1
#cmakedefine HAVE_WCHAR_H 1
#cmakedefine HAVE_WINDOWS_H 1
#cmakedefine HAVE_WINSOCK2_H 1
#cmakedefine HAVE_WS2TCPIP_H 1
#cmakedefine HAVE_SHARE_H 1
#cmakedefine HAVE_MMSYSTEM_H 1
#cmakedefine HAVE_WINIOCTL_H 1

/* ── Functions ── */

#cmakedefine HAVE_ATEXIT 1
#cmakedefine HAVE_FTRUNCATE 1
#cmakedefine HAVE_GETCWD 1
#cmakedefine HAVE_GETENTROPY 1
#cmakedefine HAVE_GETHOSTBYADDR 1
#cmakedefine HAVE_GETHOSTBYNAME 1
#cmakedefine HAVE_GETIFADDRS 1
#cmakedefine HAVE_GETPAGESIZE 1
#cmakedefine HAVE_MEMCHR 1
#cmakedefine HAVE_MEMMOVE 1
#cmakedefine HAVE_MEMPCPY 1
#cmakedefine HAVE_MEMSET 1
#cmakedefine HAVE_MKDIR 1
#cmakedefine HAVE_MMAP 1
#cmakedefine HAVE_MUNMAP 1
#cmakedefine HAVE_NL_LANGINFO 1
#cmakedefine HAVE_POSIX_FADVISE 1
#cmakedefine HAVE_POSIX_MEMALIGN 1
#cmakedefine HAVE_POW 1
#cmakedefine HAVE_PUTENV 1
#cmakedefine HAVE_RMDIR 1
#cmakedefine HAVE_SELECT 1
#cmakedefine HAVE_SETLOCALE 1
#cmakedefine HAVE_SIGACTION 1
#cmakedefine HAVE_SLEEP 1
#cmakedefine HAVE_SOCKET 1
#cmakedefine HAVE_STPCPY 1
#cmakedefine HAVE_STRCASECMP 1
#cmakedefine HAVE_STRCHR 1
#cmakedefine HAVE_STRCSPN 1
#cmakedefine HAVE_STRDUP 1
#cmakedefine HAVE_STRERROR 1
#cmakedefine HAVE_STRNCASECMP 1
#cmakedefine HAVE_STRSTR 1
#cmakedefine HAVE_STRTOL 1
#cmakedefine HAVE_STRTOUL 1
#cmakedefine HAVE_STRTOULL 1
#cmakedefine HAVE_TZSET 1
#cmakedefine HAVE_UNSETENV 1
#cmakedefine HAVE_USLEEP 1
#cmakedefine HAVE_UTIME 1
#cmakedefine HAVE_UTIMES 1
#cmakedefine HAVE_ASCTIME_R 1
#cmakedefine HAVE_LOCALTIME_R 1
#cmakedefine HAVE_BASENAME 1
#cmakedefine HAVE_GAI_STRERROR 1
#cmakedefine HAVE_GETADDRINFO 1
#cmakedefine HAVE_GETTIMEOFDAY 1
#cmakedefine HAVE_STRPTIME 1
#cmakedefine HAVE_DAEMON 1
#cmakedefine HAVE_TIMEGM 1
#cmakedefine HAVE_EPOLL_CREATE 1

/* ── Types ── */

#cmakedefine HAVE_PTRDIFF_T 1

/* Define WORDS_BIGENDIAN to 1 if your processor stores words with the most
   significant byte first (like Motorola and SPARC, unlike Intel). */
#cmakedefine WORDS_BIGENDIAN 1

/* Windows TLS */
#cmakedefine SECURITY_WIN32 1

/* GMP secure functions */
#cmakedefine HAVE_GMP_SEC 1

/* OpenSSL features */
#cmakedefine HAVE_OLD_OPENSSL 1
#cmakedefine HAVE_EVP_DIGESTINIT_EX 1
#cmakedefine HAVE_EVP_SHA224 1
#cmakedefine HAVE_EVP_SHA256 1
#cmakedefine HAVE_EVP_SHA384 1
#cmakedefine HAVE_EVP_SHA512 1

/* zlib features */
#cmakedefine HAVE_GZBUFFER 1
#cmakedefine HAVE_GZSETPARAMS 1

/* SQLite3 features */
#cmakedefine HAVE_SQLITE3_OPEN_V2 1

/* GnuTLS features */
#cmakedefine HAVE_GNUTLS_CERTIFICATE_SET_X509_SYSTEM_TRUST 1
#cmakedefine USE_GNUTLS_SYSTEM_CRYPTO_POLICY 1

/* CA bundle */
#cmakedefine CA_BUNDLE "${CA_BUNDLE}"

/* Default disk cache size */
#cmakedefine DEFAULT_DISK_CACHE "${DEFAULT_DISK_CACHE}"

/* Enable system extensions */
#ifndef _ALL_SOURCE
# define _ALL_SOURCE 1
#endif
#ifdef __APPLE__
# ifndef _DARWIN_C_SOURCE
#  define _DARWIN_C_SOURCE 1
# endif
#endif
#ifndef __EXTENSIONS__
# define __EXTENSIONS__ 1
#endif
#ifndef _GNU_SOURCE
# define _GNU_SOURCE 1
#endif
#ifndef _POSIX_PTHREAD_SEMANTICS
# define _POSIX_PTHREAD_SEMANTICS 1
#endif
#ifndef _TANDEM_SOURCE
# define _TANDEM_SOURCE 1
#endif
